#PARAMETROS
CAMERA_INDEX = 0

ONLY_RIGHT_HAND = True
RIGHT_HAND_LABEL = "Right"

MAX_HAND_BOX_RATIO = 0.58

FRAME_REDUCTION = 100
SMOOTHENING = 6

ACTION_DELAY = 0.55
ALT_TAB_DELAY = 1.2

#SOFTBARBER_EXE_PATH = r"C:\Path\To\Your\App.exe"
SOFTBARBER_EXE_PATH = r"C:\Users\LMGG1\Desktop\Softbarber\dist\SoftBarber\SoftBarber.exe"
SOFTBARBER_OPEN_DELAY = 5.0
